title = "Zoe"
description = "æˆ‘å°†æˆä¸ºæˆ‘çš„å¢“å¿—é“­"
# this filed used by manifest plugin
# which only supports:
# - project root based relative path
# - absolute path
# - remote url
# so, we must use absolute path at here
# logo = "https://github.com/jiusanzhou.png"
logo = "${__dirname}/images/avatar-v2.jpg"

version = "beta"

primaryColor = "gray"

dateFormat = "YYYY-MM-DD"

zoePlugins = [
  "src/plugins/repo-project",
  "src/plugins/blog-post",
]

gtagTrackingIds = [
    "G-5LM10G1ZPK"
]

# assetPrefix(jsdelivr) can't works well with pathPrefix
# assetPrefix = "https://cdn.jsdelivr.net/gh/jiusanzhou/gatsby-starter-zoe-app@gh-pages"

baseContentDir = [
  "${__dirname}/content"
]

[[navs]]
title = "å®éªŒé¡¹ç›®"
href = "/projects"

[[navs]]
title = "åšå®¢"
href = "/blogs"

[[navs]]
title = "å…³äº"
href = "/about"

[[links]]
title = "ä¸»é¡µ"
category = "ç«™ç‚¹"
href = "/"

[[links]]
title = "åšå®¢"
category = "ç«™ç‚¹"
href = "/blogs"

[[links]]
title = "å…³äº"
category = "ç«™ç‚¹"
href = "/about"

[[links]]
title = "é¡¹ç›®"
category = "å®éªŒ"
href = "/projects"

[[links]]
title = "RSSè®¢é˜…"
category = "å®éªŒ"
href = "/rss.xml"

[socials]
email = "hi@zoe.im"
github = "zoeim"
twitter = "jiusanzhou"
facebook = "jiusanzhou"
telegram = "jiusanzhou"
linkedin = "johnzoe"

[[projects]]
provider = "github"
tag = "zoe-lab"
owners = [ "jiusanzhou" ]

[comments]
provider = "giscus"
repo = "jiusanzhou/jiusanzhou.github.io"
repoID = "MDEwOlJlcG9zaXRvcnkxMzQ2MDAzMDM="
categoryID = "DIC_kwDOCAXWb84B-qn9"
theme = "preferred_color_scheme"

[gitContent]
name = "me"
remote = "https://jiusanzhou:${process.env.GITHUB_TOKEN}@github.com/jiusanzhou/me.git"
local = "/tmp/repo-me"
patterns = [ "ğŸ“–posts/**" ]

[[customNodes]]
name = "MdxPost"

  [customNodes.when]
  sourceName = "me"
  type = "Mdx"
  path = "ğŸ“–posts"
